### ISSUE TITLE
Accessibility props not passed through

### ISSUE THREAD

**Issue by meatnordrink** [tsepeti/react-native-dots-pagination#22]
Many approaches to creating an accessible carousel require making the dots accessible and clickable. This is messier than it needs to be currently, because the `<Dots>` component does not accept/pass-through accessibility props, so doing so requires adding an extra wrapping `<View>`. 

I've opened a PR to fix this issue - https://github.com/yasaricli/react-native-dots-pagination/pull/21.

**Comment by yasaricli** [comment]
Thanks @meatnordrink , Teşekkürler :)
