### ISSUE TITLE
componentWillReceiveProps is not recommended for use.

### ISSUE THREAD

**Issue by bfaulk96** [tsepeti/react-native-dots-pagination#3]
When using `Dots` in a react-native app, the following warning now display:
`YellowBox.js:71 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.`

This could be changed to use `componentDidUpdate()` instead and still have the desired effects.

**Comment by yasaricli** [comment]
thanks, @bfaulk96   i will review. #4

**Comment by yasaricli** [comment]
@bfaulk96  [0.1.9](https://github.com/tsepeti/react-native-dots-pagination/releases/tag/0.1.9) is published, thanks.
